### ISSUE TITLE
Post bookworm moved boot config file location

### ISSUE THREAD

**Issue by aXb0t** [alexb7217/Pi-Rack-Pro_SKU_RM0004-Install#4]
See: http://rptl.io/configtxt

> Prior to Bookworm, Raspberry Pi OS stored the boot partition at /boot/. Since Bookworm, the boot partition is located at /boot/firmware/.

Modify script for new file location, or add option for pre and post bookworm

**Comment by alexb7217** [comment]
Variable added for boot config path

Pre and post bookwork release has a variation in boot file path. Change `boot_config_path` variable in `playbook.yml` to match the path on your Pi. See: http://rptl.io/configtxt
